name: Master Deploy

env:
  SIMCUBE_SONARQUBE_ENABLED: "true"
  SIMCUBE_SONARQUBE_URL: ${{ secrets.SONAR_HOST_URL }}
  SIMCUBE_SONARQUBE_API_KEY: ${{ secrets.SONAR_TOKEN }}
  SIMCUBE_SONARQUBE_PROJECT_KEY: "CakeBuildah"
  SIMCUBE_SOLUTION_FILE_PATH: "Cake.Buildah.sln"
  SIMCUBE_BUILD_NAME: "Cake.Buildah"
  SIMCUBE_DOTNET_TOOL_PATH: ${{ secrets.TOOLS_PATH }}
  SIMCUBE_SOLUTION_ROOT: ${{ github.workspace }}
  SIMCUBE_MANUAL_VERSION: 0.0.${{ github.run_number }}.0
  SIMCUBE_MANUAL_BRANCH_NAME: ${{ github.ref_name }}
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-test-and-preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: "Install Required"
        run: |
          dotnet tool install SimCube.BuildTool --tool-path ${SIMCUBE_DOTNET_TOOL_PATH}
          dotnet tool install dotnet-sonarscanner --tool-path ${SIMCUBE_DOTNET_TOOL_PATH}

      - uses: SimCubeLtd/buildtool-action@main
        continue-on-error: false
